name: sport_app
description: "The app collects information on sports over the years."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #Config
  easy_localization: ^3.0.7+1
  go_router: ^15.1.1
  flutter_screenutil: ^5.9.3

  #Satete Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #network
  dio: ^5.8.0+1

  #Utils
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  envied: ^1.1.1
  intl: ^0.19.0

  #Local Storage
  # shared_preferences: ^2.5.3 #unused in the project

  #Third Party
  sentry_flutter: ^8.14.2

  #Widgets
  animations: ^2.0.11
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0
  flutter_gen_runner: ^5.10.0
  riverpod_generator: ^2.6.5
  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  flutter_flavorizr: ^2.4.0
  go_router_builder: ^2.9.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.1.9
  flutter_launcher_icons: ^0.14.3

# Generated assets files configuration
flutter_gen:
  assets:
    outputs:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: false



flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
