// lib/prod_env.dart
import 'package:envied/envied.dart';

part 'env.g.dart';

/// The environment variables for the app.
///
/// This class is generated by the envied package.
/// Do not edit values of the variables in this file manually.
/// Instead, edit the .env file
/// and run `dart run build_runner build` to regenerate.
@Envied(name: 'Env', path: '.env', obfuscate: false)
final class Env {
  @override
  @EnviedField(varName: 'SENTRY_DSN')
  static String SENTRY_DSN = _Env.SENTRY_DSN;

  @override
  @EnviedField(varName: 'BASE_URL')
  static String BASE_URL = _Env.BASE_URL;
}
